# Подгружаем пакеты

library(tidyverse)
library(stringr)
library(stringi)
library(rvest)
library(dplyr)
library(magrittr)
library(data.table)
library(readr)
library(glmnet)
library(plyr)
library(quanteda)
library(tidytext)
library(tidyr)
library(wordcloud)
library(caret)
library(tm)
library(cleanNLP)
library(scales)
library(readxl)
library(stopwords)
library(ggplot2)
library(igraph)
library(ggraph)
library(lubridate)